### ISSUE TITLE
Getting this error when I run Docker up

### ISSUE THREAD

**Issue by 4goodapp** [bitnami/bitnami-docker-wordpress-nginx#16]
After downloading the image version 5.3.2, I got this error when I run `docker-compose up`:

```
wordpress_1  | wordpre INFO
wordpress_1  | nami    INFO  wordpress successfully initialized
wordpress_1  | INFO  ==> Starting wordpress...
wordpress_1  | INFO  ==> Starting PHP-FPM...
wordpress_1  | INFO  ==> Starting NGINX...
wordpress_1  | 2020/02/04 01:29:51 [crit] 99#0: pread() "/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf" failed (21: Is a directory)
wordpress_1  | nginx: [crit] pread() "/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf" failed (21: Is a directory)
wordpress_nginx_2_wordpress_1 exited with code 1
```

Any idea about this issue?

Running Docker on macOS Catalina.
Images:

bitnami/wordpress-nginx           5.3.2
bitnami/mariadb                           10.3

**Comment by jotamartos** [comment]
Hi @4goodapp ,

We just reproduced the error you reported. We think you just ran the commands in the tl;dr section and they are not downloading the wordpress-server-block.conf file to your local directory and that's why it can't be mounted. If you open the docker-compose.yml file, you can see this

```
    volumes:
      - 'wordpress_data:/bitnami'
      - './wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
```

but if you don't have the .conf file in your local server, it'll create an empty directory in the container. You have two options now:

1) Stop the container, remove the volumes, download the file and start everything again

```
docker-compose down -v
rm -rf wordpress-server-block.conf
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/wordpress-server-block.conf
docker-compose up
```

NOTE: We will include this new curl command in the tl;dr section

2) Stop the container, remove the volumes and pull the whole repository with the files 

```
docker-compose down -v
cd /my/directory
git pull https://github.com/bitnami/bitnami-docker-wordpress-nginx.git
cd bitnami-docker-wordpress-nginx
docker-compose up
```

I hope this information helps

**Comment by 4goodapp** [comment]
Thanks, I figured out.
I however noticed that in Safari that `http://localhost`and `http://localhost:80` didn't point to the Wordpress default index page but to Nginx welcome page. 
I had to use http://localhost/index.php` first.

Is the `wordpress-server-block.conf`new? 
I don't remember using it first time I tried these images about one or two years ago.

**Comment by jotamartos** [comment]
You should see the WordPress' page by default because we are setting the index parameter in the .conf file. 

```
index index.php;
```

I tried to reproduce that but couldn't do so. 

![image](https://user-images.githubusercontent.com/8791635/73835694-23778980-480e-11ea-9f6c-6795705b006a.png)


Maybe you have the information cached in the web browser and that's why you are getting that page. Does that happen when using a different browser?

>Is the wordpress-server-block.conf file new?

Yes, it was created 2 months ago 

https://github.com/bitnami/bitnami-docker-wordpress-nginx/commits/master/wordpress-server-block.conf

**Comment by 4goodapp** [comment]
> Maybe you have the information cached in the web browser and that's why you are getting that page. Does that happen when using a different browser?

It was probably my cache cause in Chrome it showed the Wordpress Wellcome page. 
It's working fine now.

In the docker-compose.yml file, we have this line:
```
    Volumes:
      - 'wordpress_data:/bitnami/'
```
Which I think means the folder `wordpress_data` in our host machines is were the project code  folder is copied but it's empty.

And I noticed that based on the root section in the wordpress-server-block.conf file, the project folder in the container is inside `/opt/bitnami/wordpress` and not in `/bitnami` as specified in the `docker-compose.yml` file in volume section.

**Comment by jotamartos** [comment]
Hi @4goodapp,

The wordpress_data volume is a volume docker creates to store the app's data. We use the volume to persist its configuration when upgrading the application or recreating the container. As you can see, there is a volumes section in which the volume is defined 

```
volumes:
  wordpress_data:
    driver: local
```

You can run `docker volume ls` to list all the available volumes.

Regarding the wordpress-server-block.conf file, it's directly copied from your hard drive. As you can see, it's a relative path so it uses the file in the same directory (the volume only includes the name, not a path).
