### ISSUE TITLE
Unable to install SSL 

### ISSUE THREAD

**Issue by askmeoffers** [bitnami/bitnami-docker-wordpress-nginx#27]
Unable to install ssl please fix and guide with steps

**Comment by juan131** [comment]
Hi @askmeoffers 

Could you please provide more information?

- Are you using Docker, Docker Compose, Kubernetes?
- What version of the Bitnami NGINX container are you using?
- What steps did you follow to do so?

**Comment by askmeoffers** [comment]
Hi , 
Thanks for quickly asking me 

I am deploying on google kubernetes .

I am using latest version of Bitnami NGINX wordpress .

Steps I followed :

I installed wordpress and its works but steps for SSL and TLS are not clear 

Can you guide help us to setup steps for SSL for the same with steps 

Thanks
Team - [askmeoffers.com](https://askmeoffers.com/)

**Comment by juan131** [comment]
Hi @askmeoffers 

Thanks for clarifying these details. I still lack of information to reproduce it the issue on my side. Please share with me as many details as possible since this solution can be deployed on many different ways.

> I am using latest version of Bitnami NGINX Wordpress

Are you using the Bitnami WordPress chart or did you create your own Kubernetes manifests? If you created your own manifests, could you share them?

> I installed wordpress and its works but steps for SSL and TLS are not clear

What steps are you following? Could you please share a link to the guide or documentation you're following?
