### ISSUE TITLE
Is it possible to run CRON?

### ISSUE THREAD

**Issue by kmiskiewicz** [bitnami/bitnami-docker-wordpress-nginx#74]
### Name and Version

bitnami/wordpress-nginx:5.9.0-debian-10-r4

### What is the problem this feature will solve?

Hi, I'd like to be able to turn off the default WordPress wp_cron, and replace it with the cron scheduler. 
Is it possible? Would be great if you give me some hint how to start. 

I installed cron with 
`RUN install_packages cron `
added a task into `/etc/cron.d/`
and tried to call the command:
`CMD ["cron","-f", "-l", "2"]`
When I start the container the process just get stuck during the start. 
When I run without params just `["cron"]` I get the information 
`igamingbeatscom-webserver-1 exited with code 0 `

My dockerfile:

FROM bitnami/wordpress-nginx:5.9.0-debian-10-r4
LABEL maintainer "KM <km@km.com>"
USER 0 

RUN install_packages cron 
COPY ./wp-cron-job  /etc/cron.d/

RUN touch /var/run/crond.pid
RUN chown root:crontab /var/run/crond.pid
RUN chmod gu+rw /var/run
RUN chmod gu+s /usr/sbin/cron

USER root
CMD ["cron","-f", "-l", "2"]
USER 1001 

### What is the feature you are proposing to solve the problem?

I tried many approaches but I really got stuck

**Comment by migruiz4** [comment]
Hi @kmiskiewicz,

The simple answer would be that cron doesn't work because of this: `USER 1001`.

The more complex answer is that our containers are non-root containers, meaning that they can be run using an arbitrary user id.
This makes the containers more secure, and also allows running them on some platforms with security restrictions such as Openshift, which run containers with random UUIDs, or others that don't allow running containers as `root`.

The problem with `cron` is that it requires the user to exist inside `/etc/passwd`, therefore it can't be used by user 1001 or any other arbitrary user.

**Comment by kmiskiewicz** [comment]
Thank you for the answer, the information that something is just not possible is also a very good answer because saves a lot of time :-) I suppose in this case I could make a simple Wordpress plugin which will expose an endpoint to trigger wp-cron, and call it from some service outside.
